apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gateway-impersonate
rules:
- apiGroups:
  - ""
  resourceNames:
  - rantu.saikia@devoteam.com
  - andytzou@google.com
  - mohit.gupta@devoteam.com
  - 1007052252194@cloudbuild.gserviceaccount.com
  resources:
  - users
  verbs:
  - impersonate